"""Transforma relação Fornecedores-Estoque em N:N

Revision ID: a897691ac0fa
Revises: 752b11ae096e
Create Date: 2025-01-23 12:42:56.232155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a897691ac0fa'
down_revision: Union[str, None] = '752b11ae096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonecedores_estoque',
    sa.Column('ID_Fornecedor', sa.Integer(), nullable=False),
    sa.Column('ID_Estoque', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Estoque'], ['estoque.ID_Estoque'], ),
    sa.ForeignKeyConstraint(['ID_Fornecedor'], ['fornecedores.ID_Fornecedor'], ),
    sa.PrimaryKeyConstraint('ID_Fornecedor', 'ID_Estoque')
    )
    op.alter_column('fornecedores', 'cnpj',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fornecedores', 'cnpj',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    op.drop_table('fonecedores_estoque')
    # ### end Alembic commands ###
