logging:
    file: "app.log"
    level: "INFO"
    format: "%(asctime)s - %(levelname)s - %(message)s"
    filemode: "w"

db-connect:
    host: "localhost"
    port: "27017"
    user: ""
    password: ""
    db: "Trabalho_03"

db-populate:
    folder: "data_json"
    data_names:
        [
            "data_produtos",
            "data_clientes",
            "data_fornecedores",
            "data_produtos_fornecidos",
            "data_estoque",
            "data_vendas",
        ]
    type_files: '.json'
